services:
  spoolstats:
    container_name: spoolstats
    image: ghcr.io/edwardk9/spoolstock:latest
    ports:
      - '5000:5000'
    restart: unless-stopped
    volumes:
      - /mnt/Applications/SpoolStats/data:/app/data
